-- Seed node_types from docs/node-type-schemas.
-- Catalog changes after this migration belong in a new goose file, not an edit here.
--
-- +goose Up
-- +goose StatementBegin

INSERT INTO node_types (
    type, category, display_name,
    min_in_degree, max_in_degree, min_out_degree, max_out_degree,
    config_schema, input_schema, output_schema, error_schema
) VALUES
    ('start', 'trigger'::node_category, 'Start', 0, 0, 1, 1,
     $nt${"type":"object","properties":{"description":{"type":"string","minLength":1,"maxLength":512}},"additionalProperties":false}$nt$::jsonb,
     $nt${"type":"object","properties":{},"additionalProperties":false}$nt$::jsonb,
     $nt${"type":"object","required":["data"],"properties":{"data":{"type":"object","required":["payload"],"properties":{"payload":{"type":["object","array","string","number","boolean","null"]}},"additionalProperties":false}},"additionalProperties":false}$nt$::jsonb,
     $nt${"type":"object","required":["type","code","message","retryable"],"properties":{"type":{"type":"string","enum":["validation","internal"],"description":"Error class used for UI routing and retry policy"},"code":{"type":"string","enum":["INVALID_TRIGGER_PAYLOAD","INTERNAL_ERROR"]},"message":{"type":"string","minLength":1,"maxLength":512,"description":"Short user-facing summary"},"description":{"type":"string","minLength":1,"maxLength":2048,"description":"Optional remediation guidance shown in run history"},"retryable":{"type":"boolean"},"retry_after_ms":{"type":"integer","minimum":0,"maximum":3600000},"details":{"type":"object","properties":{"parameter":{"type":"string","maxLength":256,"description":"Config or input field that caused the failure"},"cause":{"type":"string","maxLength":4096}},"additionalProperties":false}},"additionalProperties":false}$nt$::jsonb),
    ('conditional', 'logic'::node_category, 'Conditional', 1, 1, 2, 2,
     $nt${"type":"object","required":["expression"],"properties":{"expression":{"type":"string","minLength":1,"maxLength":4096,"description":"Boolean expression over input.data, e.g. data.payload.status == 200"}},"additionalProperties":false}$nt$::jsonb,
     $nt${"type":"object","required":["data"],"properties":{"data":{"type":"object","additionalProperties":true}},"additionalProperties":false}$nt$::jsonb,
     $nt${"type":"object","required":["data"],"properties":{"data":{"type":"object","required":["branch"],"properties":{"branch":{"type":"string","enum":["true","false"]}},"additionalProperties":true}},"additionalProperties":false}$nt$::jsonb,
     $nt${"type":"object","required":["type","code","message","retryable"],"properties":{"type":{"type":"string","enum":["validation","operation","internal"],"description":"Error class used for UI routing and retry policy"},"code":{"type":"string","enum":["INVALID_INPUT","EXPRESSION_ERROR","INTERNAL_ERROR"]},"message":{"type":"string","minLength":1,"maxLength":512,"description":"Short user-facing summary"},"description":{"type":"string","minLength":1,"maxLength":2048,"description":"Optional remediation guidance shown in run history"},"retryable":{"type":"boolean"},"retry_after_ms":{"type":"integer","minimum":0,"maximum":3600000},"details":{"type":"object","properties":{"parameter":{"type":"string","maxLength":256,"description":"Config or input field that caused the failure"},"expression":{"type":"string","maxLength":4096},"cause":{"type":"string","maxLength":4096}},"additionalProperties":false}},"additionalProperties":false}$nt$::jsonb),
    ('function', 'logic'::node_category, 'Function', 1, 1, 1, 1,
     $nt${"type":"object","required":["runtime","source"],"properties":{"runtime":{"const":"js"},"source":{"type":"string","minLength":1,"maxLength":65536,"description":"Function body; receives input.data, must return a value"},"timeout_ms":{"type":"integer","minimum":1,"maximum":300000,"default":5000}},"additionalProperties":false}$nt$::jsonb,
     $nt${"type":"object","required":["data"],"properties":{"data":{"type":"object","additionalProperties":true}},"additionalProperties":false}$nt$::jsonb,
     $nt${"type":"object","required":["data"],"properties":{"data":{"type":["object","array","string","number","boolean","null"]}},"additionalProperties":false}$nt$::jsonb,
     $nt${"type":"object","required":["type","code","message","retryable"],"properties":{"type":{"type":"string","enum":["validation","operation","timeout","internal"],"description":"Error class used for UI routing and retry policy"},"code":{"type":"string","enum":["INVALID_INPUT","RUNTIME_ERROR","TIMEOUT","INTERNAL_ERROR"]},"message":{"type":"string","minLength":1,"maxLength":512,"description":"Short user-facing summary"},"description":{"type":"string","minLength":1,"maxLength":2048,"description":"Optional remediation guidance shown in run history"},"retryable":{"type":"boolean"},"retry_after_ms":{"type":"integer","minimum":0,"maximum":3600000},"details":{"type":"object","properties":{"parameter":{"type":"string","maxLength":256,"description":"Config or input field that caused the failure"},"runtime":{"const":"js"},"timeout_ms":{"type":"integer","minimum":1,"maximum":300000},"stack":{"type":"string","maxLength":16384},"cause":{"type":"string","maxLength":4096}},"additionalProperties":false}},"additionalProperties":false}$nt$::jsonb),
    ('api', 'action'::node_category, 'General API', 1, 1, 1, 1,
     $nt${"type":"object","required":["method","url"],"properties":{"method":{"type":"string","enum":["GET","POST","PUT","PATCH","DELETE","QUERY"]},"url":{"type":"string","minLength":1,"maxLength":2048,"format":"uri-template"},"headers":{"type":"object","propertyNames":{"type":"string","minLength":1,"maxLength":256,"pattern":"^[A-Za-z0-9!#$%&'*+.^_`|~-]+$"},"additionalProperties":{"type":"string","maxLength":8192}},"query":{"type":"object","propertyNames":{"type":"string","minLength":1,"maxLength":256},"additionalProperties":{"type":"string","maxLength":4096}},"body_template":{"type":"string","minLength":1,"maxLength":65536,"description":"Optional template over input.data"},"timeout_ms":{"type":"integer","minimum":1,"maximum":300000,"default":30000}},"additionalProperties":false}$nt$::jsonb,
     $nt${"type":"object","required":["data"],"properties":{"data":{"type":"object","additionalProperties":true}},"additionalProperties":false}$nt$::jsonb,
     $nt${"type":"object","required":["data"],"properties":{"data":{"type":"object","required":["status","headers","body"],"properties":{"status":{"type":"integer","enum":[100,101,102,103,200,201,202,203,204,205,206,207,208,226,300,301,302,303,304,305,307,308,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,421,422,423,424,425,426,428,429,431,451,500,501,502,503,504,505,506,507,508,510,511]},"headers":{"type":"object","propertyNames":{"type":"string","minLength":1,"maxLength":256,"pattern":"^[A-Za-z0-9!#$%&'*+.^_`|~-]+$"},"additionalProperties":{"type":"string","maxLength":8192}},"body":{"type":["object","array","string","number","boolean","null"]}},"additionalProperties":false}},"additionalProperties":false}$nt$::jsonb,
     $nt${"type":"object","required":["type","code","message","retryable"],"properties":{"type":{"type":"string","enum":["validation","api","timeout","rate_limit","internal"],"description":"Error class used for UI routing and retry policy"},"code":{"type":"string","enum":["INVALID_INPUT","INVALID_CONFIG","HTTP_NON_2XX","TIMEOUT","NETWORK_ERROR","RATE_LIMITED","INTERNAL_ERROR"]},"message":{"type":"string","minLength":1,"maxLength":512,"description":"Short user-facing summary"},"description":{"type":"string","minLength":1,"maxLength":2048,"description":"Optional remediation guidance shown in run history"},"retryable":{"type":"boolean"},"retry_after_ms":{"type":"integer","minimum":0,"maximum":3600000,"description":"Suggested delay before retry (e.g. rate limits)"},"http_status":{"type":"integer","enum":[100,101,102,103,200,201,202,203,204,205,206,207,208,226,300,301,302,303,304,305,307,308,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,421,422,423,424,425,426,428,429,431,451,500,501,502,503,504,505,506,507,508,510,511]},"details":{"type":"object","properties":{"parameter":{"type":"string","maxLength":256,"description":"Config or input field that caused the failure"},"method":{"type":"string","enum":["GET","POST","PUT","PATCH","DELETE","QUERY"]},"url":{"type":"string","maxLength":2048},"response_headers":{"type":"object","propertyNames":{"type":"string","minLength":1,"maxLength":256,"pattern":"^[A-Za-z0-9!#$%&'*+.^_`|~-]+$"},"additionalProperties":{"type":"string","maxLength":8192}},"response_body":{"type":["object","array","string","number","boolean","null"]},"timeout_ms":{"type":"integer","minimum":1,"maximum":300000},"cause":{"type":"string","maxLength":4096}},"additionalProperties":false}},"additionalProperties":false}$nt$::jsonb),
    ('response', 'terminal'::node_category, 'Response', 1, 1, 0, 0,
     $nt${"type":"object","required":["status_code"],"properties":{"status_code":{"type":"integer","enum":[100,101,102,103,200,201,202,203,204,205,206,207,208,226,300,301,302,303,304,305,307,308,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,421,422,423,424,425,426,428,429,431,451,500,501,502,503,504,505,506,507,508,510,511],"default":200},"body_template":{"type":"string","minLength":1,"maxLength":65536,"description":"Template over input.data for final response body"},"headers":{"type":"object","propertyNames":{"type":"string","minLength":1,"maxLength":256,"pattern":"^[A-Za-z0-9!#$%&'*+.^_`|~-]+$"},"additionalProperties":{"type":"string","maxLength":8192}}},"additionalProperties":false}$nt$::jsonb,
     $nt${"type":"object","required":["data"],"properties":{"data":{"type":"object","additionalProperties":true}},"additionalProperties":false}$nt$::jsonb,
     $nt${"type":"object","required":["data"],"properties":{"data":{"type":"object","required":["status_code","body"],"properties":{"status_code":{"type":"integer","enum":[100,101,102,103,200,201,202,203,204,205,206,207,208,226,300,301,302,303,304,305,307,308,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,421,422,423,424,425,426,428,429,431,451,500,501,502,503,504,505,506,507,508,510,511]},"headers":{"type":"object","propertyNames":{"type":"string","minLength":1,"maxLength":256,"pattern":"^[A-Za-z0-9!#$%&'*+.^_`|~-]+$"},"additionalProperties":{"type":"string","maxLength":8192}},"body":{"type":["object","array","string","number","boolean","null"]}},"additionalProperties":false}},"additionalProperties":false}$nt$::jsonb,
     $nt${"type":"object","required":["type","code","message","retryable"],"properties":{"type":{"type":"string","enum":["validation","operation","internal"],"description":"Error class used for UI routing and retry policy"},"code":{"type":"string","enum":["INVALID_INPUT","TEMPLATE_ERROR","INTERNAL_ERROR"]},"message":{"type":"string","minLength":1,"maxLength":512,"description":"Short user-facing summary"},"description":{"type":"string","minLength":1,"maxLength":2048,"description":"Optional remediation guidance shown in run history"},"retryable":{"type":"boolean"},"retry_after_ms":{"type":"integer","minimum":0,"maximum":3600000},"details":{"type":"object","properties":{"parameter":{"type":"string","maxLength":256,"description":"Config or input field that caused the failure"},"template":{"type":"string","maxLength":65536},"cause":{"type":"string","maxLength":4096}},"additionalProperties":false}},"additionalProperties":false}$nt$::jsonb)
ON CONFLICT (type) DO UPDATE SET
    category = EXCLUDED.category,
    display_name = EXCLUDED.display_name,
    min_in_degree = EXCLUDED.min_in_degree,
    max_in_degree = EXCLUDED.max_in_degree,
    min_out_degree = EXCLUDED.min_out_degree,
    max_out_degree = EXCLUDED.max_out_degree,
    config_schema = EXCLUDED.config_schema,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema,
    error_schema = EXCLUDED.error_schema;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DELETE FROM node_types WHERE type IN ('start', 'conditional', 'function', 'api', 'response');

-- +goose StatementEnd
