# One-shot goose migration image (local compose + prod ECS run-task).
# Pin linux/amd64 so images built on Apple Silicon still run on Fargate.
FROM --platform=linux/amd64 golang:1.26-alpine
RUN go install github.com/pressly/goose/v3/cmd/goose@v3.27.3

WORKDIR /migrations
COPY db/migrations/ /migrations/

ENV GOOSE_DRIVER=postgres
ENV GOOSE_MIGRATION_DIR=/migrations

ENTRYPOINT ["goose"]
CMD ["up"]
