# One-shot migration image for local docker compose.

FROM golang:1.26-alpine
RUN go install github.com/pressly/goose/v3/cmd/goose@v3.27.3

WORKDIR /migrations
COPY db/migrations/ /migrations/

ENV GOOSE_DRIVER=postgres
ENV GOOSE_MIGRATION_DIR=/migrations

ENTRYPOINT ["goose"]
CMD ["up"]
