// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type WorkflowStatus string

const (
	WorkflowStatusDraft     WorkflowStatus = "draft"
	WorkflowStatusPublished WorkflowStatus = "published"
	WorkflowStatusArchived  WorkflowStatus = "archived"
)

func (e *WorkflowStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkflowStatus(s)
	case string:
		*e = WorkflowStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkflowStatus: %T", src)
	}
	return nil
}

type NullWorkflowStatus struct {
	WorkflowStatus WorkflowStatus `json:"workflow_status"`
	Valid          bool           `json:"valid"` // Valid is true if WorkflowStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkflowStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorkflowStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkflowStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkflowStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkflowStatus), nil
}

type Workflow struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	Description     *string        `json:"description"`
	Status          WorkflowStatus `json:"status"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	LastPublishedAt *time.Time     `json:"last_published_at"`
}
