// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const deleteNodesNotIn = `-- name: DeleteNodesNotIn :exec
DELETE FROM nodes
WHERE workflow_version_id = $1
  AND (
      cardinality($2::uuid[]) = 0
      OR id <> ALL ($2::uuid[])
  )
`

type DeleteNodesNotInParams struct {
	WorkflowVersionID uuid.UUID   `json:"workflow_version_id"`
	Ids               []uuid.UUID `json:"ids"`
}

// cardinality 0 (empty payload) deletes every node in the version.
func (q *Queries) DeleteNodesNotIn(ctx context.Context, arg DeleteNodesNotInParams) error {
	_, err := q.db.Exec(ctx, deleteNodesNotIn, arg.WorkflowVersionID, arg.Ids)
	return err
}

const listNodesForPublish = `-- name: ListNodesForPublish :many
SELECT
    n.id,
    nt.type,
    nt.min_in_degree,
    nt.max_in_degree,
    nt.min_out_degree,
    nt.max_out_degree
FROM nodes n
INNER JOIN node_types nt ON nt.id = n.node_type_id
WHERE n.workflow_version_id = $1
`

type ListNodesForPublishRow struct {
	ID           uuid.UUID `json:"id"`
	Type         string    `json:"type"`
	MinInDegree  int32     `json:"min_in_degree"`
	MaxInDegree  int32     `json:"max_in_degree"`
	MinOutDegree int32     `json:"min_out_degree"`
	MaxOutDegree int32     `json:"max_out_degree"`
}

// PK prefix (workflow_version_id, id); join node_types by PK for degree bounds.
func (q *Queries) ListNodesForPublish(ctx context.Context, workflowVersionID uuid.UUID) ([]ListNodesForPublishRow, error) {
	rows, err := q.db.Query(ctx, listNodesForPublish, workflowVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodesForPublishRow{}
	for rows.Next() {
		var i ListNodesForPublishRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.MinInDegree,
			&i.MaxInDegree,
			&i.MinOutDegree,
			&i.MaxOutDegree,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNodes = `-- name: UpsertNodes :exec
INSERT INTO nodes (
    id,
    workflow_version_id,
    node_type_id,
    name,
    config,
    position_x,
    position_y
)
SELECT
    (e->>'id')::uuid,
    $1,
    (e->>'node_type_id')::uuid,
    e->>'name',
    '{}'::jsonb,
    NULLIF(e->>'position_x', '')::double precision,
    NULLIF(e->>'position_y', '')::double precision
FROM jsonb_array_elements($2::jsonb) AS t(e)
ON CONFLICT (workflow_version_id, id) DO UPDATE SET
    node_type_id = EXCLUDED.node_type_id,
    name = EXCLUDED.name,
    config = EXCLUDED.config,
    position_x = EXCLUDED.position_x,
    position_y = EXCLUDED.position_y
`

type UpsertNodesParams struct {
	WorkflowVersionID uuid.UUID       `json:"workflow_version_id"`
	Nodes             json.RawMessage `json:"nodes"`
}

func (q *Queries) UpsertNodes(ctx context.Context, arg UpsertNodesParams) error {
	_, err := q.db.Exec(ctx, upsertNodes, arg.WorkflowVersionID, arg.Nodes)
	return err
}
