// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node_types.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const listNodeTypes = `-- name: ListNodeTypes :many
SELECT id, type, config_schema
FROM node_types
`

type ListNodeTypesRow struct {
	ID           uuid.UUID       `json:"id"`
	Type         string          `json:"type"`
	ConfigSchema json.RawMessage `json:"config_schema"`
}

func (q *Queries) ListNodeTypes(ctx context.Context) ([]ListNodeTypesRow, error) {
	rows, err := q.db.Query(ctx, listNodeTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodeTypesRow{}
	for rows.Next() {
		var i ListNodeTypesRow
		if err := rows.Scan(&i.ID, &i.Type, &i.ConfigSchema); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
