// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow_edges.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const deleteEdgesNotIn = `-- name: DeleteEdgesNotIn :exec
DELETE FROM workflow_edges
WHERE workflow_version_id = $1
  AND (
      cardinality($2::uuid[]) = 0
      OR id <> ALL ($2::uuid[])
  )
`

type DeleteEdgesNotInParams struct {
	WorkflowVersionID uuid.UUID   `json:"workflow_version_id"`
	Ids               []uuid.UUID `json:"ids"`
}

// cardinality 0 (empty payload) deletes every edge in the version.
func (q *Queries) DeleteEdgesNotIn(ctx context.Context, arg DeleteEdgesNotInParams) error {
	_, err := q.db.Exec(ctx, deleteEdgesNotIn, arg.WorkflowVersionID, arg.Ids)
	return err
}

const listEdgesForPublish = `-- name: ListEdgesForPublish :many
SELECT id, from_node_id, to_node_id, label
FROM workflow_edges
WHERE workflow_version_id = $1
`

type ListEdgesForPublishRow struct {
	ID         uuid.UUID `json:"id"`
	FromNodeID uuid.UUID `json:"from_node_id"`
	ToNodeID   uuid.UUID `json:"to_node_id"`
	Label      EdgeLabel `json:"label"`
}

// PK prefix (workflow_version_id, id). No sort: validation does not need order.
func (q *Queries) ListEdgesForPublish(ctx context.Context, workflowVersionID uuid.UUID) ([]ListEdgesForPublishRow, error) {
	rows, err := q.db.Query(ctx, listEdgesForPublish, workflowVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEdgesForPublishRow{}
	for rows.Next() {
		var i ListEdgesForPublishRow
		if err := rows.Scan(
			&i.ID,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEdges = `-- name: UpsertEdges :exec
INSERT INTO workflow_edges (
    id,
    workflow_version_id,
    from_node_id,
    to_node_id,
    label
)
SELECT
    (e->>'id')::uuid,
    $1,
    (e->>'from_node_id')::uuid,
    (e->>'to_node_id')::uuid,
    (e->>'label')::edge_label
FROM jsonb_array_elements($2::jsonb) AS t(e)
ON CONFLICT (workflow_version_id, id) DO UPDATE SET
    from_node_id = EXCLUDED.from_node_id,
    to_node_id = EXCLUDED.to_node_id,
    label = EXCLUDED.label
`

type UpsertEdgesParams struct {
	WorkflowVersionID uuid.UUID       `json:"workflow_version_id"`
	Edges             json.RawMessage `json:"edges"`
}

func (q *Queries) UpsertEdges(ctx context.Context, arg UpsertEdgesParams) error {
	_, err := q.db.Exec(ctx, upsertEdges, arg.WorkflowVersionID, arg.Edges)
	return err
}
