// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow_runs.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const advanceWorkflowRun = `-- name: AdvanceWorkflowRun :exec
UPDATE workflow_runs
SET
    status = 'running',
    current_node_id = $1,
    current_node_attempt = 1,
    last_output = $2
WHERE id = $3
`

type AdvanceWorkflowRunParams struct {
	CurrentNodeID uuid.UUID       `json:"current_node_id"`
	LastOutput    json.RawMessage `json:"last_output"`
	ID            uuid.UUID       `json:"id"`
}

func (q *Queries) AdvanceWorkflowRun(ctx context.Context, arg AdvanceWorkflowRunParams) error {
	_, err := q.db.Exec(ctx, advanceWorkflowRun, arg.CurrentNodeID, arg.LastOutput, arg.ID)
	return err
}

const completeWorkflowRun = `-- name: CompleteWorkflowRun :exec
UPDATE workflow_runs
SET
    status = 'completed',
    last_output = $1,
    completed_at = now()
WHERE id = $2
`

type CompleteWorkflowRunParams struct {
	LastOutput json.RawMessage `json:"last_output"`
	ID         uuid.UUID       `json:"id"`
}

func (q *Queries) CompleteWorkflowRun(ctx context.Context, arg CompleteWorkflowRunParams) error {
	_, err := q.db.Exec(ctx, completeWorkflowRun, arg.LastOutput, arg.ID)
	return err
}

const deleteRunNodeJobOutbox = `-- name: DeleteRunNodeJobOutbox :exec
DELETE FROM run_node_jobs_outbox
WHERE id = $1
`

func (q *Queries) DeleteRunNodeJobOutbox(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRunNodeJobOutbox, id)
	return err
}

const failWorkflowRun = `-- name: FailWorkflowRun :exec
UPDATE workflow_runs
SET
    status = 'failed',
    error = jsonb_build_object('message', $1::text),
    failed_at = now(),
    current_node_attempt = current_node_attempt + 1
WHERE id = $2
`

type FailWorkflowRunParams struct {
	ErrorMessage string    `json:"error_message"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) FailWorkflowRun(ctx context.Context, arg FailWorkflowRunParams) error {
	_, err := q.db.Exec(ctx, failWorkflowRun, arg.ErrorMessage, arg.ID)
	return err
}

const getPublishedWorkflowForStart = `-- name: GetPublishedWorkflowForStart :one
SELECT
    w.id,
    w.latest_published_version_id,
    COALESCE(s.id, '00000000-0000-0000-0000-000000000000'::uuid) AS start_node_id
FROM workflows w
LEFT JOIN (
    SELECT n.workflow_version_id, n.id
    FROM nodes n
    INNER JOIN node_types nt ON nt.id = n.node_type_id
    WHERE nt.type = 'start'
) s ON s.workflow_version_id = w.latest_published_version_id
WHERE w.id = $1
  AND w.status = 'published'
`

type GetPublishedWorkflowForStartRow struct {
	ID                       uuid.UUID  `json:"id"`
	LatestPublishedVersionID *uuid.UUID `json:"latest_published_version_id"`
	StartNodeID              uuid.UUID  `json:"start_node_id"`
}

// Published workflow plus that version's Start node.
// LEFT JOIN keeps a published row when Start is missing so the handler can 500
// instead of treating it as an unpublished 404.
// COALESCE: sqlc types nodes.id as NOT NULL even on this LEFT JOIN, so a
// missing Start would fail Scan. The zero UUID is the missing-Start marker.
func (q *Queries) GetPublishedWorkflowForStart(ctx context.Context, id uuid.UUID) (GetPublishedWorkflowForStartRow, error) {
	row := q.db.QueryRow(ctx, getPublishedWorkflowForStart, id)
	var i GetPublishedWorkflowForStartRow
	err := row.Scan(&i.ID, &i.LatestPublishedVersionID, &i.StartNodeID)
	return i, err
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
SELECT id, workflow_id, workflow_version_id, status, trigger_type, current_node_id, current_node_attempt, last_output, error, started_at, paused_at, cancelled_at, completed_at, failed_at, created_at, updated_at
FROM workflow_runs
WHERE id = $1
`

func (q *Queries) GetWorkflowRun(ctx context.Context, id uuid.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.Status,
		&i.TriggerType,
		&i.CurrentNodeID,
		&i.CurrentNodeAttempt,
		&i.LastOutput,
		&i.Error,
		&i.StartedAt,
		&i.PausedAt,
		&i.CancelledAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRunNodeJobOutbox = `-- name: InsertRunNodeJobOutbox :exec
INSERT INTO run_node_jobs_outbox (
    run_id,
    workflow_version_id,
    node_id,
    attempt
) VALUES (
    $1,
    $2,
    $3,
    1
)
`

type InsertRunNodeJobOutboxParams struct {
	RunID             uuid.UUID `json:"run_id"`
	WorkflowVersionID uuid.UUID `json:"workflow_version_id"`
	NodeID            uuid.UUID `json:"node_id"`
}

func (q *Queries) InsertRunNodeJobOutbox(ctx context.Context, arg InsertRunNodeJobOutboxParams) error {
	_, err := q.db.Exec(ctx, insertRunNodeJobOutbox, arg.RunID, arg.WorkflowVersionID, arg.NodeID)
	return err
}

const insertWorkflowRun = `-- name: InsertWorkflowRun :one
INSERT INTO workflow_runs (
    workflow_id,
    workflow_version_id,
    status,
    trigger_type,
    current_node_id,
    current_node_attempt,
    last_output,
    started_at
) VALUES (
    $1,
    $2,
    'pending',
    'manual',
    $3,
    1,
    $4,
    now()
)
RETURNING id, workflow_id, workflow_version_id, status, trigger_type, current_node_id, current_node_attempt, last_output, error, started_at, paused_at, cancelled_at, completed_at, failed_at, created_at, updated_at
`

type InsertWorkflowRunParams struct {
	WorkflowID        uuid.UUID       `json:"workflow_id"`
	WorkflowVersionID uuid.UUID       `json:"workflow_version_id"`
	CurrentNodeID     uuid.UUID       `json:"current_node_id"`
	LastOutput        json.RawMessage `json:"last_output"`
}

func (q *Queries) InsertWorkflowRun(ctx context.Context, arg InsertWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, insertWorkflowRun,
		arg.WorkflowID,
		arg.WorkflowVersionID,
		arg.CurrentNodeID,
		arg.LastOutput,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.Status,
		&i.TriggerType,
		&i.CurrentNodeID,
		&i.CurrentNodeAttempt,
		&i.LastOutput,
		&i.Error,
		&i.StartedAt,
		&i.PausedAt,
		&i.CancelledAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockDueRunNodeJobsOutbox = `-- name: LockDueRunNodeJobsOutbox :many
SELECT
    o.id,
    o.run_id,
    o.workflow_version_id,
    o.node_id,
    o.attempt,
    r.status AS run_status
FROM run_node_jobs_outbox o
JOIN workflow_runs r ON r.id = o.run_id
WHERE o.available_at IS NULL OR o.available_at < now()
ORDER BY o.created_at
FOR UPDATE OF o, r SKIP LOCKED
`

type LockDueRunNodeJobsOutboxRow struct {
	ID                uuid.UUID         `json:"id"`
	RunID             uuid.UUID         `json:"run_id"`
	WorkflowVersionID uuid.UUID         `json:"workflow_version_id"`
	NodeID            uuid.UUID         `json:"node_id"`
	Attempt           int32             `json:"attempt"`
	RunStatus         WorkflowRunStatus `json:"run_status"`
}

func (q *Queries) LockDueRunNodeJobsOutbox(ctx context.Context) ([]LockDueRunNodeJobsOutboxRow, error) {
	rows, err := q.db.Query(ctx, lockDueRunNodeJobsOutbox)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockDueRunNodeJobsOutboxRow{}
	for rows.Next() {
		var i LockDueRunNodeJobsOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.WorkflowVersionID,
			&i.NodeID,
			&i.Attempt,
			&i.RunStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseWorkflowRun = `-- name: PauseWorkflowRun :one
UPDATE workflow_runs
SET
    status = 'paused',
    paused_at = COALESCE(paused_at, now())
WHERE id = $1
  AND status IN ('pending', 'running', 'paused')
RETURNING id, workflow_id, workflow_version_id, status, trigger_type, current_node_id, current_node_attempt, last_output, error, started_at, paused_at, cancelled_at, completed_at, failed_at, created_at, updated_at
`

// Soft pause: pending|running → paused; already paused is idempotent (keep paused_at).
// Handler checks WorkflowRunExists first; no row here means terminal status → 409.
func (q *Queries) PauseWorkflowRun(ctx context.Context, id uuid.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, pauseWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.Status,
		&i.TriggerType,
		&i.CurrentNodeID,
		&i.CurrentNodeAttempt,
		&i.LastOutput,
		&i.Error,
		&i.StartedAt,
		&i.PausedAt,
		&i.CancelledAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resumeWorkflowRun = `-- name: ResumeWorkflowRun :one
UPDATE workflow_runs
SET
    status = 'running',
    paused_at = NULL
WHERE id = $1
  AND status = 'paused'
RETURNING id, workflow_id, workflow_version_id, status, trigger_type, current_node_id, current_node_attempt, last_output, error, started_at, paused_at, cancelled_at, completed_at, failed_at, created_at, updated_at
`

// Resume: paused → running. Handler checks exists first; no row → 409.
func (q *Queries) ResumeWorkflowRun(ctx context.Context, id uuid.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, resumeWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.Status,
		&i.TriggerType,
		&i.CurrentNodeID,
		&i.CurrentNodeAttempt,
		&i.LastOutput,
		&i.Error,
		&i.StartedAt,
		&i.PausedAt,
		&i.CancelledAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retryWorkflowRun = `-- name: RetryWorkflowRun :one
UPDATE workflow_runs
SET
    status = 'running',
    failed_at = NULL,
    error = NULL,
    current_node_attempt = 1
WHERE id = $1
  AND status = 'failed'
RETURNING id, workflow_id, workflow_version_id, status, trigger_type, current_node_id, current_node_attempt, last_output, error, started_at, paused_at, cancelled_at, completed_at, failed_at, created_at, updated_at
`

// Retry: failed → running; clear failure markers and reset attempt.
// Handler checks exists first; no row → 409.
func (q *Queries) RetryWorkflowRun(ctx context.Context, id uuid.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, retryWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.Status,
		&i.TriggerType,
		&i.CurrentNodeID,
		&i.CurrentNodeAttempt,
		&i.LastOutput,
		&i.Error,
		&i.StartedAt,
		&i.PausedAt,
		&i.CancelledAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const stopWorkflowRun = `-- name: StopWorkflowRun :one
UPDATE workflow_runs
SET
    status = 'cancelled',
    cancelled_at = COALESCE(cancelled_at, now())
WHERE id = $1
  AND status IN ('pending', 'running', 'paused', 'cancelled')
RETURNING id, workflow_id, workflow_version_id, status, trigger_type, current_node_id, current_node_attempt, last_output, error, started_at, paused_at, cancelled_at, completed_at, failed_at, created_at, updated_at
`

// Stop: pending|running|paused → cancelled; already cancelled is idempotent.
// Handler checks exists first; completed|failed → no row → 409.
func (q *Queries) StopWorkflowRun(ctx context.Context, id uuid.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, stopWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.Status,
		&i.TriggerType,
		&i.CurrentNodeID,
		&i.CurrentNodeAttempt,
		&i.LastOutput,
		&i.Error,
		&i.StartedAt,
		&i.PausedAt,
		&i.CancelledAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const workflowRunExists = `-- name: WorkflowRunExists :one
SELECT EXISTS(
    SELECT 1
    FROM workflow_runs
    WHERE id = $1
)
`

func (q *Queries) WorkflowRunExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, workflowRunExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
