// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow_versions.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const createWorkflowVersion = `-- name: CreateWorkflowVersion :one
INSERT INTO workflow_versions (workflow_id, version)
SELECT $1, COALESCE(MAX(version), 0) + 1
FROM workflow_versions
WHERE workflow_id = $1
RETURNING
    id,
    workflow_id,
    version,
    created_at,
    last_updated_at,
    published_at
`

func (q *Queries) CreateWorkflowVersion(ctx context.Context, workflowID uuid.UUID) (WorkflowVersion, error) {
	row := q.db.QueryRow(ctx, createWorkflowVersion, workflowID)
	var i WorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Version,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const touchWorkflowVersion = `-- name: TouchWorkflowVersion :exec
UPDATE workflow_versions
SET version = version
WHERE id = $1
`

func (q *Queries) TouchWorkflowVersion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchWorkflowVersion, id)
	return err
}
