// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflows.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const getWorkflow = `-- name: GetWorkflow :one
SELECT
    id,
    name,
    description,
    status,
    created_at,
    updated_at,
    last_published_at
FROM workflows
WHERE id = $1
  AND status != 'archived'
`

func (q *Queries) GetWorkflow(ctx context.Context, id uuid.UUID) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPublishedAt,
	)
	return i, err
}
