include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

aws {
  region = ap-south-1
  accountId = 000000000000
}

queues {
  orchex-node-jobs {
    defaultVisibilityTimeout = 60 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "orchex-node-jobs-dlq"
      maxReceiveCount = 5
    }
  }

  orchex-node-jobs-dlq {}
}
